### ISSUE TITLE
Question: compatibility with other addon

### ISSUE THREAD

**Issue by Grossdm** [siyangqiu/FFTextWrap#3]
Hello again,

I have been trying out another addon to darken webpages [Dark Background and Light Text](https://addons.mozilla.org/android/addon/dark-background-light-text).

Sometimes page behavior is a little "off" - hard to describe.

I think that both your addon and DBLT ([GitHub repo](https://github.com/m-khvoinitsky/dark-background-light-text-extension)) interact with the css.

Might there be a conflict with both running?

TIA

Doug®

**Comment by siyangqiu** [comment]
Hi Doug, 

Sorry for the terribly late response. 

There shouldn't be a conflict between the add-ons. I looked through the source code of the add-on and didn't find anything that should conflict.

Regarding the "off" behavior, could you describe it in a bit more detail? Are you refering to how the add-on tries to recenter on what you were looking at before the zoom?

**Comment by Grossdm** [comment]
Hello @siyangqiu,

The late response is unacceptable. I demand a full refund! 😁

I suspect that I was mistaken about any behavior caused by a conflict between the addons.
The DBLT addon is like a love/hate situation: on many sites it seems to darken every element perfectly. On others it doesn't work with its default setting, and the other choices often seem to cause problems with the browser.

To answer your question, yes I really struggle with FFTextWrap trying to recenter.

Often it (apparently) gives up and the page scrolls to the top. (That is with the following file "Natural" setting, BTW.)

I'm sure that you are familiar with how well Opera handles reflowing of text.
Can you explain why Fennec struggles so much with this (I guess with no addon it doesn't bother to try!) and how Opera does it so well?


Thank you for your help and for the addon!

Doug®

**Comment by siyangqiu** [comment]
I actually have no idea how Opera does it since it's closed source. I was actually under the impression that Opera doesn't recenter. I try to do more testing and see what I can do about this. 

I set "natural" look at the top most HTML element that is 20 pixels down and right from the top left corner of the screen (I should probably rename this). After the reflow, Firefox is set to scroll to that element. If there isn't anything there, the top most element might be the body of the web page that begins at the absolute top right of the page. Also, if you are using Firefox Nightly, there seems to be a bug with how the element at point function is implemented in the latest version.

Anyhow, if the feature is giving you grief, I would try another one of the modes or just turn it off entirely. I also welcome any suggestions on how to refocus Firefox. 

Thanks for all your feedback by the way.

**Comment by siyangqiu** [comment]
I did some testing. I think Opera anchors to the part of the web page that your last finger on the screen is around. (whereas the addon finds an element and sends that to the top of the screen). I'll see if I can implement Opera's version that well.

**Comment by Grossdm** [comment]
If you could make Firefox reflow text like Opera, well, you'd be my hero! :grinning:
