### ISSUE TITLE
page header also enlarges and blocks page

### ISSUE THREAD

**Issue by spthomas01** [siyangqiu/FFTextWrap#4]
this does work like Opera, but when you zoom to enlarge, not only does it enlarge the text and wrap it, but the header of the page is enlarged too.  This often obscures the entire page so you can't see the text.  Opera doesn't do that, so it's a doable thing.  

Check this link on an Android phone:

https://www.investopedia.com/articles/personal-finance/071014/medigap-vs-medicare-advantage-which-better.asp

**Comment by siyangqiu** [comment]
Unfortunately, I think this is a Firefox issue (at least with regards to this website), rather than an issue with my add-on. Even with my add-on disabled, the banner expands when you zoom in. Firefox uses its own rendering engine (Gecko) rather than Blink (used in Opera and Chrome). Feel free to reopen this issue if you think my add-on is interacting with this somehow.
